version: '3'
services:
  kali:
    network_mode: host
    build: .
    stdin_open: true
    tty: true
    command: "/usr/bin/zsh"
    container_name: "kali"
    restart:
      always
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN

    volumes:
      - ~/share:/root/share/
      - $HOME/.Xauthority:/root/.Xauthority-n
    ipc: host

    environment:
      - DISPLAY=$DISPLAY
